version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r function.zip .
artifacts:
  files:
    - function.zip